apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-parent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dori654/Portfolio-Develeap-GitOps.git
    targetRevision: HEAD
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: cat-agency
  syncPolicy:
    automated:
      prune: true
      selfHeal: true